package net.tonimatasdev.fastregions.api.flag;

public enum Flag {
    block_break,
    block_place,
    block_spread,
    block_grow,
    block_shears,
    block_fertilize,
    block_dispense,
    block_exp,
    block_burn,
    block_drop,
    tnt_prime,
    note_play,
    leaves_decay,
    sponge_absorb,
    block_ignite,
    sign_change,
    redstone,
    piston,
    snowman_snow,
    frost_walker,
    cauldron_interact,
    respawn_anchor_explode,
    bed_explode,
    bell_ring,
    sensor,
    raid,
    vehicle_create,
    vehicle_damage,
    vehicle_destroy,
    vehicle_enter,
}
